name: extrawest_ui_kit
description: Flutter package that provides Extrawest UI Kit based on Material 3 UI components
version: 0.0.2
homepage: https://www.extrawest.com/
repository: https://github.com/extrawest/extrawest_ui_kit_mobile
issue_tracker: https://github.com/extrawest/extrawest_ui_kit_mobile/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.6.0
  formz: ^0.6.1
  intl_phone_number_input: ^0.7.3+1
  password_strength: ^0.2.0
  sms_autofill: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

screenshots:
  - description: 'Extrawest logo'
    path: example/extrawest_logo.png

topics:
  - design
  - extrawest
  - ui